[package]
name = "reef-test"
version = "0.0.4"
edition = "2021"
description = "A test set for SeasideVPN reef library"
authors = [
    "Alexander Sergeev <alexander.sergeev@onmail.com>"
]



[dependencies]
regex = "^1.11.1"
simple-error = "^0.3.1"



[lib]
name = "reeftest"
path = "lib/mod.rs"
